### ISSUE TITLE
Footer icons are broken

### ISSUE THREAD

**Issue by grepsedawk** [pachonk/pachonk.github.io#1]

**Comment by d4rkd0s** [comment]
[Copied post from #2]

Loading this resource over HTTPS when the site is HTTP (http://alexpiechowski.com/) is causing the social media icons at the bottom of the screen to not load.

![image](https://user-images.githubusercontent.com/2348814/30405486-005de936-98a1-11e7-8696-bc4527da5d29.png)

https://github.com/pachonk/pachonk.github.io/blob/8914116dc354f7136ae7492b08d163c29cf593e7/index.html#L13

**Comment by grepsedawk** [comment]
Thanks for pointing out the reason they weren't loading
